---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca
    hooks:
      - id: actionlint
