---
name: CI

"on":
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read

  test:
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read

  security:
    uses: ./.github/workflows/security.yml
    permissions:
      contents: read
